AWS_UPLOAD_BUCKET = 'indeed-upload'

AWS_UPLOAD_USERNAME = 'suhail'

AWS_UPLOAD_GROUP = 'e-distribution-group'

AWS_UPLOAD_REGION = 'us-west-2'

AWS_UPLOAD_ACCESS_KEY_ID = 'AKIAJXXSBF6SJHUJ3QKA'

AWS_UPLOAD_SECRET_KEY = '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'